// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: api/proto/v2/fastpath.proto

package fastpathv2

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FastPathService_CreateSandbox_FullMethodName         = "/fastpath.v2.FastPathService/CreateSandbox"
	FastPathService_DeleteSandbox_FullMethodName         = "/fastpath.v2.FastPathService/DeleteSandbox"
	FastPathService_UpdateSandbox_FullMethodName         = "/fastpath.v2.FastPathService/UpdateSandbox"
	FastPathService_ListSandboxes_FullMethodName         = "/fastpath.v2.FastPathService/ListSandboxes"
	FastPathService_GetSandbox_FullMethodName            = "/fastpath.v2.FastPathService/GetSandbox"
	FastPathService_GetSandboxDiagnostics_FullMethodName = "/fastpath.v2.FastPathService/GetSandboxDiagnostics"
	FastPathService_ResolveEndpoint_FullMethodName       = "/fastpath.v2.FastPathService/ResolveEndpoint"
	FastPathService_GetPool_FullMethodName               = "/fastpath.v2.FastPathService/GetPool"
	FastPathService_ListPools_FullMethodName             = "/fastpath.v2.FastPathService/ListPools"
	FastPathService_CreateSandboxSnapshot_FullMethodName = "/fastpath.v2.FastPathService/CreateSandboxSnapshot"
	FastPathService_GetSandboxSnapshot_FullMethodName    = "/fastpath.v2.FastPathService/GetSandboxSnapshot"
	FastPathService_DeleteSandboxSnapshot_FullMethodName = "/fastpath.v2.FastPathService/DeleteSandboxSnapshot"
)

// FastPathServiceClient is the client API for FastPathService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FastPathServiceClient interface {
	CreateSandbox(ctx context.Context, in *CreateSandboxRequest, opts ...grpc.CallOption) (*CreateSandboxResponse, error)
	DeleteSandbox(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	UpdateSandbox(ctx context.Context, in *UpdateSandboxRequest, opts ...grpc.CallOption) (*UpdateSandboxResponse, error)
	ListSandboxes(ctx context.Context, in *ListSandboxesRequest, opts ...grpc.CallOption) (*ListSandboxesResponse, error)
	GetSandbox(ctx context.Context, in *GetSandboxRequest, opts ...grpc.CallOption) (*GetSandboxResponse, error)
	GetSandboxDiagnostics(ctx context.Context, in *SandboxDiagnosticsRequest, opts ...grpc.CallOption) (*SandboxDiagnosticsResponse, error)
	ResolveEndpoint(ctx context.Context, in *ResolveEndpointRequest, opts ...grpc.CallOption) (*ResolveEndpointResponse, error)
	GetPool(ctx context.Context, in *GetPoolRequest, opts ...grpc.CallOption) (*PoolInfo, error)
	ListPools(ctx context.Context, in *ListPoolsRequest, opts ...grpc.CallOption) (*ListPoolsResponse, error)
	// CreateSandboxSnapshot snapshots a running Sandbox and publishes the
	// artifact set to the artifact store under the snapshot's template name.
	// It returns after the intent is persisted and the snapshot is triggered;
	// completion is observed via GetSandboxSnapshot.
	CreateSandboxSnapshot(ctx context.Context, in *CreateSandboxSnapshotRequest, opts ...grpc.CallOption) (*CreateSandboxSnapshotResponse, error)
	GetSandboxSnapshot(ctx context.Context, in *GetSandboxSnapshotRequest, opts ...grpc.CallOption) (*GetSandboxSnapshotResponse, error)
	DeleteSandboxSnapshot(ctx context.Context, in *DeleteSandboxSnapshotRequest, opts ...grpc.CallOption) (*DeleteSandboxSnapshotResponse, error)
}

type fastPathServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFastPathServiceClient(cc grpc.ClientConnInterface) FastPathServiceClient {
	return &fastPathServiceClient{cc}
}

func (c *fastPathServiceClient) CreateSandbox(ctx context.Context, in *CreateSandboxRequest, opts ...grpc.CallOption) (*CreateSandboxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSandboxResponse)
	err := c.cc.Invoke(ctx, FastPathService_CreateSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fastPathServiceClient) DeleteSandbox(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, FastPathService_DeleteSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fastPathServiceClient) UpdateSandbox(ctx context.Context, in *UpdateSandboxRequest, opts ...grpc.CallOption) (*UpdateSandboxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSandboxResponse)
	err := c.cc.Invoke(ctx, FastPathService_UpdateSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fastPathServiceClient) ListSandboxes(ctx context.Context, in *ListSandboxesRequest, opts ...grpc.CallOption) (*ListSandboxesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSandboxesResponse)
	err := c.cc.Invoke(ctx, FastPathService_ListSandboxes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fastPathServiceClient) GetSandbox(ctx context.Context, in *GetSandboxRequest, opts ...grpc.CallOption) (*GetSandboxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSandboxResponse)
	err := c.cc.Invoke(ctx, FastPathService_GetSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fastPathServiceClient) GetSandboxDiagnostics(ctx context.Context, in *SandboxDiagnosticsRequest, opts ...grpc.CallOption) (*SandboxDiagnosticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SandboxDiagnosticsResponse)
	err := c.cc.Invoke(ctx, FastPathService_GetSandboxDiagnostics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fastPathServiceClient) ResolveEndpoint(ctx context.Context, in *ResolveEndpointRequest, opts ...grpc.CallOption) (*ResolveEndpointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveEndpointResponse)
	err := c.cc.Invoke(ctx, FastPathService_ResolveEndpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fastPathServiceClient) GetPool(ctx context.Context, in *GetPoolRequest, opts ...grpc.CallOption) (*PoolInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PoolInfo)
	err := c.cc.Invoke(ctx, FastPathService_GetPool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fastPathServiceClient) ListPools(ctx context.Context, in *ListPoolsRequest, opts ...grpc.CallOption) (*ListPoolsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPoolsResponse)
	err := c.cc.Invoke(ctx, FastPathService_ListPools_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fastPathServiceClient) CreateSandboxSnapshot(ctx context.Context, in *CreateSandboxSnapshotRequest, opts ...grpc.CallOption) (*CreateSandboxSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSandboxSnapshotResponse)
	err := c.cc.Invoke(ctx, FastPathService_CreateSandboxSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fastPathServiceClient) GetSandboxSnapshot(ctx context.Context, in *GetSandboxSnapshotRequest, opts ...grpc.CallOption) (*GetSandboxSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSandboxSnapshotResponse)
	err := c.cc.Invoke(ctx, FastPathService_GetSandboxSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fastPathServiceClient) DeleteSandboxSnapshot(ctx context.Context, in *DeleteSandboxSnapshotRequest, opts ...grpc.CallOption) (*DeleteSandboxSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSandboxSnapshotResponse)
	err := c.cc.Invoke(ctx, FastPathService_DeleteSandboxSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FastPathServiceServer is the server API for FastPathService service.
// All implementations must embed UnimplementedFastPathServiceServer
// for forward compatibility.
type FastPathServiceServer interface {
	CreateSandbox(context.Context, *CreateSandboxRequest) (*CreateSandboxResponse, error)
	DeleteSandbox(context.Context, *DeleteRequest) (*DeleteResponse, error)
	UpdateSandbox(context.Context, *UpdateSandboxRequest) (*UpdateSandboxResponse, error)
	ListSandboxes(context.Context, *ListSandboxesRequest) (*ListSandboxesResponse, error)
	GetSandbox(context.Context, *GetSandboxRequest) (*GetSandboxResponse, error)
	GetSandboxDiagnostics(context.Context, *SandboxDiagnosticsRequest) (*SandboxDiagnosticsResponse, error)
	ResolveEndpoint(context.Context, *ResolveEndpointRequest) (*ResolveEndpointResponse, error)
	GetPool(context.Context, *GetPoolRequest) (*PoolInfo, error)
	ListPools(context.Context, *ListPoolsRequest) (*ListPoolsResponse, error)
	// CreateSandboxSnapshot snapshots a running Sandbox and publishes the
	// artifact set to the artifact store under the snapshot's template name.
	// It returns after the intent is persisted and the snapshot is triggered;
	// completion is observed via GetSandboxSnapshot.
	CreateSandboxSnapshot(context.Context, *CreateSandboxSnapshotRequest) (*CreateSandboxSnapshotResponse, error)
	GetSandboxSnapshot(context.Context, *GetSandboxSnapshotRequest) (*GetSandboxSnapshotResponse, error)
	DeleteSandboxSnapshot(context.Context, *DeleteSandboxSnapshotRequest) (*DeleteSandboxSnapshotResponse, error)
	mustEmbedUnimplementedFastPathServiceServer()
}

// UnimplementedFastPathServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFastPathServiceServer struct{}

func (UnimplementedFastPathServiceServer) CreateSandbox(context.Context, *CreateSandboxRequest) (*CreateSandboxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSandbox not implemented")
}
func (UnimplementedFastPathServiceServer) DeleteSandbox(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSandbox not implemented")
}
func (UnimplementedFastPathServiceServer) UpdateSandbox(context.Context, *UpdateSandboxRequest) (*UpdateSandboxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSandbox not implemented")
}
func (UnimplementedFastPathServiceServer) ListSandboxes(context.Context, *ListSandboxesRequest) (*ListSandboxesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSandboxes not implemented")
}
func (UnimplementedFastPathServiceServer) GetSandbox(context.Context, *GetSandboxRequest) (*GetSandboxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSandbox not implemented")
}
func (UnimplementedFastPathServiceServer) GetSandboxDiagnostics(context.Context, *SandboxDiagnosticsRequest) (*SandboxDiagnosticsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSandboxDiagnostics not implemented")
}
func (UnimplementedFastPathServiceServer) ResolveEndpoint(context.Context, *ResolveEndpointRequest) (*ResolveEndpointResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveEndpoint not implemented")
}
func (UnimplementedFastPathServiceServer) GetPool(context.Context, *GetPoolRequest) (*PoolInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPool not implemented")
}
func (UnimplementedFastPathServiceServer) ListPools(context.Context, *ListPoolsRequest) (*ListPoolsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPools not implemented")
}
func (UnimplementedFastPathServiceServer) CreateSandboxSnapshot(context.Context, *CreateSandboxSnapshotRequest) (*CreateSandboxSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSandboxSnapshot not implemented")
}
func (UnimplementedFastPathServiceServer) GetSandboxSnapshot(context.Context, *GetSandboxSnapshotRequest) (*GetSandboxSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSandboxSnapshot not implemented")
}
func (UnimplementedFastPathServiceServer) DeleteSandboxSnapshot(context.Context, *DeleteSandboxSnapshotRequest) (*DeleteSandboxSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSandboxSnapshot not implemented")
}
func (UnimplementedFastPathServiceServer) mustEmbedUnimplementedFastPathServiceServer() {}
func (UnimplementedFastPathServiceServer) testEmbeddedByValue()                         {}

// UnsafeFastPathServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FastPathServiceServer will
// result in compilation errors.
type UnsafeFastPathServiceServer interface {
	mustEmbedUnimplementedFastPathServiceServer()
}

func RegisterFastPathServiceServer(s grpc.ServiceRegistrar, srv FastPathServiceServer) {
	// If the following call panics, it indicates UnimplementedFastPathServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FastPathService_ServiceDesc, srv)
}

func _FastPathService_CreateSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FastPathServiceServer).CreateSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FastPathService_CreateSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FastPathServiceServer).CreateSandbox(ctx, req.(*CreateSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FastPathService_DeleteSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FastPathServiceServer).DeleteSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FastPathService_DeleteSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FastPathServiceServer).DeleteSandbox(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FastPathService_UpdateSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FastPathServiceServer).UpdateSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FastPathService_UpdateSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FastPathServiceServer).UpdateSandbox(ctx, req.(*UpdateSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FastPathService_ListSandboxes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSandboxesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FastPathServiceServer).ListSandboxes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FastPathService_ListSandboxes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FastPathServiceServer).ListSandboxes(ctx, req.(*ListSandboxesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FastPathService_GetSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FastPathServiceServer).GetSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FastPathService_GetSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FastPathServiceServer).GetSandbox(ctx, req.(*GetSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FastPathService_GetSandboxDiagnostics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SandboxDiagnosticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FastPathServiceServer).GetSandboxDiagnostics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FastPathService_GetSandboxDiagnostics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FastPathServiceServer).GetSandboxDiagnostics(ctx, req.(*SandboxDiagnosticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FastPathService_ResolveEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveEndpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FastPathServiceServer).ResolveEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FastPathService_ResolveEndpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FastPathServiceServer).ResolveEndpoint(ctx, req.(*ResolveEndpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FastPathService_GetPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FastPathServiceServer).GetPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FastPathService_GetPool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FastPathServiceServer).GetPool(ctx, req.(*GetPoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FastPathService_ListPools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPoolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FastPathServiceServer).ListPools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FastPathService_ListPools_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FastPathServiceServer).ListPools(ctx, req.(*ListPoolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FastPathService_CreateSandboxSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSandboxSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FastPathServiceServer).CreateSandboxSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FastPathService_CreateSandboxSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FastPathServiceServer).CreateSandboxSnapshot(ctx, req.(*CreateSandboxSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FastPathService_GetSandboxSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSandboxSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FastPathServiceServer).GetSandboxSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FastPathService_GetSandboxSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FastPathServiceServer).GetSandboxSnapshot(ctx, req.(*GetSandboxSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FastPathService_DeleteSandboxSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSandboxSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FastPathServiceServer).DeleteSandboxSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FastPathService_DeleteSandboxSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FastPathServiceServer).DeleteSandboxSnapshot(ctx, req.(*DeleteSandboxSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FastPathService_ServiceDesc is the grpc.ServiceDesc for FastPathService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FastPathService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fastpath.v2.FastPathService",
	HandlerType: (*FastPathServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSandbox",
			Handler:    _FastPathService_CreateSandbox_Handler,
		},
		{
			MethodName: "DeleteSandbox",
			Handler:    _FastPathService_DeleteSandbox_Handler,
		},
		{
			MethodName: "UpdateSandbox",
			Handler:    _FastPathService_UpdateSandbox_Handler,
		},
		{
			MethodName: "ListSandboxes",
			Handler:    _FastPathService_ListSandboxes_Handler,
		},
		{
			MethodName: "GetSandbox",
			Handler:    _FastPathService_GetSandbox_Handler,
		},
		{
			MethodName: "GetSandboxDiagnostics",
			Handler:    _FastPathService_GetSandboxDiagnostics_Handler,
		},
		{
			MethodName: "ResolveEndpoint",
			Handler:    _FastPathService_ResolveEndpoint_Handler,
		},
		{
			MethodName: "GetPool",
			Handler:    _FastPathService_GetPool_Handler,
		},
		{
			MethodName: "ListPools",
			Handler:    _FastPathService_ListPools_Handler,
		},
		{
			MethodName: "CreateSandboxSnapshot",
			Handler:    _FastPathService_CreateSandboxSnapshot_Handler,
		},
		{
			MethodName: "GetSandboxSnapshot",
			Handler:    _FastPathService_GetSandboxSnapshot_Handler,
		},
		{
			MethodName: "DeleteSandboxSnapshot",
			Handler:    _FastPathService_DeleteSandboxSnapshot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/v2/fastpath.proto",
}
