# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import fastpath_pb2 as fastpath__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in fastpath_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FastPathServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSandbox = channel.unary_unary(
                '/fastpath.v1.FastPathService/CreateSandbox',
                request_serializer=fastpath__pb2.CreateRequest.SerializeToString,
                response_deserializer=fastpath__pb2.CreateResponse.FromString,
                _registered_method=True)
        self.DeleteSandbox = channel.unary_unary(
                '/fastpath.v1.FastPathService/DeleteSandbox',
                request_serializer=fastpath__pb2.DeleteRequest.SerializeToString,
                response_deserializer=fastpath__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.UpdateSandbox = channel.unary_unary(
                '/fastpath.v1.FastPathService/UpdateSandbox',
                request_serializer=fastpath__pb2.UpdateRequest.SerializeToString,
                response_deserializer=fastpath__pb2.UpdateResponse.FromString,
                _registered_method=True)
        self.ListSandboxes = channel.unary_unary(
                '/fastpath.v1.FastPathService/ListSandboxes',
                request_serializer=fastpath__pb2.ListRequest.SerializeToString,
                response_deserializer=fastpath__pb2.ListResponse.FromString,
                _registered_method=True)
        self.GetSandbox = channel.unary_unary(
                '/fastpath.v1.FastPathService/GetSandbox',
                request_serializer=fastpath__pb2.GetRequest.SerializeToString,
                response_deserializer=fastpath__pb2.SandboxInfo.FromString,
                _registered_method=True)
        self.GetSandboxDiagnostics = channel.unary_unary(
                '/fastpath.v1.FastPathService/GetSandboxDiagnostics',
                request_serializer=fastpath__pb2.SandboxDiagnosticsRequest.SerializeToString,
                response_deserializer=fastpath__pb2.SandboxDiagnosticsResponse.FromString,
                _registered_method=True)
        self.ResolveEndpoint = channel.unary_unary(
                '/fastpath.v1.FastPathService/ResolveEndpoint',
                request_serializer=fastpath__pb2.ResolveEndpointRequest.SerializeToString,
                response_deserializer=fastpath__pb2.ResolveEndpointResponse.FromString,
                _registered_method=True)
        self.IssueRouteCredential = channel.unary_unary(
                '/fastpath.v1.FastPathService/IssueRouteCredential',
                request_serializer=fastpath__pb2.IssueRouteCredentialRequest.SerializeToString,
                response_deserializer=fastpath__pb2.IssueRouteCredentialResponse.FromString,
                _registered_method=True)


class FastPathServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateSandbox(self, request, context):
        """CreateSandbox performs the imperative CRD-first low-latency path: one CRD
        Create followed by one atomic Fastlet Create on the happy path.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSandbox(self, request, context):
        """DeleteSandbox commits declarative deletion; Controller reconciliation owns cleanup.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSandbox(self, request, context):
        """UpdateSandbox commits declarative expiry, reset, or failure-policy intent.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSandboxes(self, request, context):
        """ListSandboxes 获取沙箱列表
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSandbox(self, request, context):
        """GetSandbox 获取沙箱详情
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSandboxDiagnostics(self, request, context):
        """GetSandboxDiagnostics returns platform lifecycle diagnostics. It never
        depends on an injected user-space Infra Component such as execd.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResolveEndpoint(self, request, context):
        """ResolveEndpoint resolves an authenticated proxy route for a target port.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IssueRouteCredential(self, request, context):
        """IssueRouteCredential refreshes a short-lived credential for an existing route.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FastPathServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSandbox': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSandbox,
                    request_deserializer=fastpath__pb2.CreateRequest.FromString,
                    response_serializer=fastpath__pb2.CreateResponse.SerializeToString,
            ),
            'DeleteSandbox': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSandbox,
                    request_deserializer=fastpath__pb2.DeleteRequest.FromString,
                    response_serializer=fastpath__pb2.DeleteResponse.SerializeToString,
            ),
            'UpdateSandbox': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSandbox,
                    request_deserializer=fastpath__pb2.UpdateRequest.FromString,
                    response_serializer=fastpath__pb2.UpdateResponse.SerializeToString,
            ),
            'ListSandboxes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSandboxes,
                    request_deserializer=fastpath__pb2.ListRequest.FromString,
                    response_serializer=fastpath__pb2.ListResponse.SerializeToString,
            ),
            'GetSandbox': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSandbox,
                    request_deserializer=fastpath__pb2.GetRequest.FromString,
                    response_serializer=fastpath__pb2.SandboxInfo.SerializeToString,
            ),
            'GetSandboxDiagnostics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSandboxDiagnostics,
                    request_deserializer=fastpath__pb2.SandboxDiagnosticsRequest.FromString,
                    response_serializer=fastpath__pb2.SandboxDiagnosticsResponse.SerializeToString,
            ),
            'ResolveEndpoint': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolveEndpoint,
                    request_deserializer=fastpath__pb2.ResolveEndpointRequest.FromString,
                    response_serializer=fastpath__pb2.ResolveEndpointResponse.SerializeToString,
            ),
            'IssueRouteCredential': grpc.unary_unary_rpc_method_handler(
                    servicer.IssueRouteCredential,
                    request_deserializer=fastpath__pb2.IssueRouteCredentialRequest.FromString,
                    response_serializer=fastpath__pb2.IssueRouteCredentialResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fastpath.v1.FastPathService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fastpath.v1.FastPathService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FastPathService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateSandbox(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fastpath.v1.FastPathService/CreateSandbox',
            fastpath__pb2.CreateRequest.SerializeToString,
            fastpath__pb2.CreateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSandbox(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fastpath.v1.FastPathService/DeleteSandbox',
            fastpath__pb2.DeleteRequest.SerializeToString,
            fastpath__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSandbox(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fastpath.v1.FastPathService/UpdateSandbox',
            fastpath__pb2.UpdateRequest.SerializeToString,
            fastpath__pb2.UpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSandboxes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fastpath.v1.FastPathService/ListSandboxes',
            fastpath__pb2.ListRequest.SerializeToString,
            fastpath__pb2.ListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSandbox(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fastpath.v1.FastPathService/GetSandbox',
            fastpath__pb2.GetRequest.SerializeToString,
            fastpath__pb2.SandboxInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSandboxDiagnostics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fastpath.v1.FastPathService/GetSandboxDiagnostics',
            fastpath__pb2.SandboxDiagnosticsRequest.SerializeToString,
            fastpath__pb2.SandboxDiagnosticsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResolveEndpoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fastpath.v1.FastPathService/ResolveEndpoint',
            fastpath__pb2.ResolveEndpointRequest.SerializeToString,
            fastpath__pb2.ResolveEndpointResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IssueRouteCredential(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fastpath.v1.FastPathService/IssueRouteCredential',
            fastpath__pb2.IssueRouteCredentialRequest.SerializeToString,
            fastpath__pb2.IssueRouteCredentialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
