// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: api/proto/v1/fastpath.proto

package fastpathv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ConsistencyMode 定义创建 sandbox 的一致性模式
type ConsistencyMode int32

const (
	// FAST 模式：先创建 Fastlet，后写 CRD（默认）
	// 最低延迟，但 CRD 写入失败可能导致正在使用的 sandbox 被清理
	ConsistencyMode_FAST ConsistencyMode = 0
	// STRONG 模式：先写 CRD，后创建 Fastlet
	// 延迟略高，但保证强一致性
	ConsistencyMode_STRONG ConsistencyMode = 1
)

// Enum value maps for ConsistencyMode.
var (
	ConsistencyMode_name = map[int32]string{
		0: "FAST",
		1: "STRONG",
	}
	ConsistencyMode_value = map[string]int32{
		"FAST":   0,
		"STRONG": 1,
	}
)

func (x ConsistencyMode) Enum() *ConsistencyMode {
	p := new(ConsistencyMode)
	*p = x
	return p
}

func (x ConsistencyMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConsistencyMode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_v1_fastpath_proto_enumTypes[0].Descriptor()
}

func (ConsistencyMode) Type() protoreflect.EnumType {
	return &file_api_proto_v1_fastpath_proto_enumTypes[0]
}

func (x ConsistencyMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConsistencyMode.Descriptor instead.
func (ConsistencyMode) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_v1_fastpath_proto_rawDescGZIP(), []int{0}
}

// FailurePolicy 定义故障恢复策略
type FailurePolicy int32

const (
	FailurePolicy_MANUAL        FailurePolicy = 0 // 仅报告状态，不自动恢复
	FailurePolicy_AUTO_RECREATE FailurePolicy = 1 // 自动重新调度
)

// Enum value maps for FailurePolicy.
var (
	FailurePolicy_name = map[int32]string{
		0: "MANUAL",
		1: "AUTO_RECREATE",
	}
	FailurePolicy_value = map[string]int32{
		"MANUAL":        0,
		"AUTO_RECREATE": 1,
	}
)

func (x FailurePolicy) Enum() *FailurePolicy {
	p := new(FailurePolicy)
	*p = x
	return p
}

func (x FailurePolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FailurePolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_v1_fastpath_proto_enumTypes[1].Descriptor()
}

func (FailurePolicy) Type() protoreflect.EnumType {
	return &file_api_proto_v1_fastpath_proto_enumTypes[1]
}

func (x FailurePolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FailurePolicy.Descriptor instead.
func (FailurePolicy) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_v1_fastpath_proto_rawDescGZIP(), []int{1}
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_api_proto_v1_fastpath_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_fastpath_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_fastpath_proto_rawDescGZIP(), []int{0}
}

func (x *ListRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*SandboxInfo         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_api_proto_v1_fastpath_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_fastpath_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_fastpath_proto_rawDescGZIP(), []int{1}
}

func (x *ListResponse) GetItems() []*SandboxInfo {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxName   string                 `protobuf:"bytes,1,opt,name=sandbox_name,json=sandboxName,proto3" json:"sandbox_name,omitempty"` // CRD name (user-provided)
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`                        // optional, default "default"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_api_proto_v1_fastpath_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_fastpath_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_fastpath_proto_rawDescGZIP(), []int{2}
}

func (x *GetRequest) GetSandboxName() string {
	if x != nil {
		return x.SandboxName
	}
	return ""
}

func (x *GetRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type SandboxInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`       // container ID (md5 hash or UID)
	SandboxName   string                 `protobuf:"bytes,8,opt,name=sandbox_name,json=sandboxName,proto3" json:"sandbox_name,omitempty"` // CRD name (user-provided)
	Phase         string                 `protobuf:"bytes,2,opt,name=phase,proto3" json:"phase,omitempty"`
	FastletPod    string                 `protobuf:"bytes,3,opt,name=fastlet_pod,json=fastletPod,proto3" json:"fastlet_pod,omitempty"`
	Endpoints     []string               `protobuf:"bytes,4,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Image         string                 `protobuf:"bytes,6,opt,name=image,proto3" json:"image,omitempty"`
	PoolRef       string                 `protobuf:"bytes,7,opt,name=pool_ref,json=poolRef,proto3" json:"pool_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxInfo) Reset() {
	*x = SandboxInfo{}
	mi := &file_api_proto_v1_fastpath_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxInfo) ProtoMessage() {}

func (x *SandboxInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_fastpath_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxInfo.ProtoReflect.Descriptor instead.
func (*SandboxInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_fastpath_proto_rawDescGZIP(), []int{3}
}

func (x *SandboxInfo) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *SandboxInfo) GetSandboxName() string {
	if x != nil {
		return x.SandboxName
	}
	return ""
}

func (x *SandboxInfo) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *SandboxInfo) GetFastletPod() string {
	if x != nil {
		return x.FastletPod
	}
	return ""
}

func (x *SandboxInfo) GetEndpoints() []string {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *SandboxInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *SandboxInfo) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *SandboxInfo) GetPoolRef() string {
	if x != nil {
		return x.PoolRef
	}
	return ""
}

type CreateRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Image   string                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	PoolRef string                 `protobuf:"bytes,2,opt,name=pool_ref,json=poolRef,proto3" json:"pool_ref,omitempty"`
	// Deprecated: Marked as deprecated in api/proto/v1/fastpath.proto.
	ExposedPorts []int32  `protobuf:"varint,3,rep,packed,name=exposed_ports,json=exposedPorts,proto3" json:"exposed_ports,omitempty"`
	Command      []string `protobuf:"bytes,4,rep,name=command,proto3" json:"command,omitempty"`
	Args         []string `protobuf:"bytes,5,rep,name=args,proto3" json:"args,omitempty"`
	Namespace    string   `protobuf:"bytes,6,opt,name=namespace,proto3" json:"namespace,omitempty"` // 可选，默认为 "default"
	// Deprecated: Marked as deprecated in api/proto/v1/fastpath.proto.
	ConsistencyMode ConsistencyMode   `protobuf:"varint,7,opt,name=consistency_mode,json=consistencyMode,proto3,enum=fastpath.v1.ConsistencyMode" json:"consistency_mode,omitempty"`
	Name            string            `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`                                                                           // 可选，指定沙箱名称（用于测试故障注入）
	Envs            map[string]string `protobuf:"bytes,9,rep,name=envs,proto3" json:"envs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 环境变量
	WorkingDir      string            `protobuf:"bytes,10,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`                                            // 工作目录
	RequestId       string            `protobuf:"bytes,11,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`                                               // stable idempotency key, generated by SDK/fastctl when omitted
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_api_proto_v1_fastpath_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_fastpath_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_fastpath_proto_rawDescGZIP(), []int{4}
}

func (x *CreateRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *CreateRequest) GetPoolRef() string {
	if x != nil {
		return x.PoolRef
	}
	return ""
}

// Deprecated: Marked as deprecated in api/proto/v1/fastpath.proto.
func (x *CreateRequest) GetExposedPorts() []int32 {
	if x != nil {
		return x.ExposedPorts
	}
	return nil
}

func (x *CreateRequest) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *CreateRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *CreateRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

// Deprecated: Marked as deprecated in api/proto/v1/fastpath.proto.
func (x *CreateRequest) GetConsistencyMode() ConsistencyMode {
	if x != nil {
		return x.ConsistencyMode
	}
	return ConsistencyMode_FAST
}

func (x *CreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRequest) GetEnvs() map[string]string {
	if x != nil {
		return x.Envs
	}
	return nil
}

func (x *CreateRequest) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *CreateRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type CreateResponse struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	SandboxId   string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`       // container ID (md5 hash or UID)
	SandboxName string                 `protobuf:"bytes,4,opt,name=sandbox_name,json=sandboxName,proto3" json:"sandbox_name,omitempty"` // CRD name (user-provided)
	FastletPod  string                 `protobuf:"bytes,2,opt,name=fastlet_pod,json=fastletPod,proto3" json:"fastlet_pod,omitempty"`
	// Deprecated: Marked as deprecated in api/proto/v1/fastpath.proto.
	Endpoints     []string `protobuf:"bytes,3,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	SandboxUid    string   `protobuf:"bytes,5,opt,name=sandbox_uid,json=sandboxUid,proto3" json:"sandbox_uid,omitempty"` // Kubernetes Sandbox CRD UID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_api_proto_v1_fastpath_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_fastpath_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_fastpath_proto_rawDescGZIP(), []int{5}
}

func (x *CreateResponse) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *CreateResponse) GetSandboxName() string {
	if x != nil {
		return x.SandboxName
	}
	return ""
}

func (x *CreateResponse) GetFastletPod() string {
	if x != nil {
		return x.FastletPod
	}
	return ""
}

// Deprecated: Marked as deprecated in api/proto/v1/fastpath.proto.
func (x *CreateResponse) GetEndpoints() []string {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *CreateResponse) GetSandboxUid() string {
	if x != nil {
		return x.SandboxUid
	}
	return ""
}

type ResolveEndpointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxUid    string                 `protobuf:"bytes,1,opt,name=sandbox_uid,json=sandboxUid,proto3" json:"sandbox_uid,omitempty"`
	TargetPort    uint32                 `protobuf:"varint,2,opt,name=target_port,json=targetPort,proto3" json:"target_port,omitempty"`
	Protocol      string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"` // http, https, grpc, tcp; initial proxy support is profile-dependent
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveEndpointRequest) Reset() {
	*x = ResolveEndpointRequest{}
	mi := &file_api_proto_v1_fastpath_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveEndpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveEndpointRequest) ProtoMessage() {}

func (x *ResolveEndpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_fastpath_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveEndpointRequest.ProtoReflect.Descriptor instead.
func (*ResolveEndpointRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_fastpath_proto_rawDescGZIP(), []int{6}
}

func (x *ResolveEndpointRequest) GetSandboxUid() string {
	if x != nil {
		return x.SandboxUid
	}
	return ""
}

func (x *ResolveEndpointRequest) GetTargetPort() uint32 {
	if x != nil {
		return x.TargetPort
	}
	return 0
}

func (x *ResolveEndpointRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

type ResolveEndpointResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	SandboxUid           string                 `protobuf:"bytes,1,opt,name=sandbox_uid,json=sandboxUid,proto3" json:"sandbox_uid,omitempty"`
	TargetPort           uint32                 `protobuf:"varint,2,opt,name=target_port,json=targetPort,proto3" json:"target_port,omitempty"`
	ProxyEndpoint        string                 `protobuf:"bytes,3,opt,name=proxy_endpoint,json=proxyEndpoint,proto3" json:"proxy_endpoint,omitempty"`
	RequiredHeaders      map[string]string      `protobuf:"bytes,4,rep,name=required_headers,json=requiredHeaders,proto3" json:"required_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RouteGeneration      int64                  `protobuf:"varint,5,opt,name=route_generation,json=routeGeneration,proto3" json:"route_generation,omitempty"`
	ExpiresAtUnixSeconds int64                  `protobuf:"varint,6,opt,name=expires_at_unix_seconds,json=expiresAtUnixSeconds,proto3" json:"expires_at_unix_seconds,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ResolveEndpointResponse) Reset() {
	*x = ResolveEndpointResponse{}
	mi := &file_api_proto_v1_fastpath_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveEndpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveEndpointResponse) ProtoMessage() {}

func (x *ResolveEndpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_fastpath_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveEndpointResponse.ProtoReflect.Descriptor instead.
func (*ResolveEndpointResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_fastpath_proto_rawDescGZIP(), []int{7}
}

func (x *ResolveEndpointResponse) GetSandboxUid() string {
	if x != nil {
		return x.SandboxUid
	}
	return ""
}

func (x *ResolveEndpointResponse) GetTargetPort() uint32 {
	if x != nil {
		return x.TargetPort
	}
	return 0
}

func (x *ResolveEndpointResponse) GetProxyEndpoint() string {
	if x != nil {
		return x.ProxyEndpoint
	}
	return ""
}

func (x *ResolveEndpointResponse) GetRequiredHeaders() map[string]string {
	if x != nil {
		return x.RequiredHeaders
	}
	return nil
}

func (x *ResolveEndpointResponse) GetRouteGeneration() int64 {
	if x != nil {
		return x.RouteGeneration
	}
	return 0
}

func (x *ResolveEndpointResponse) GetExpiresAtUnixSeconds() int64 {
	if x != nil {
		return x.ExpiresAtUnixSeconds
	}
	return 0
}

type IssueRouteCredentialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxUid    string                 `protobuf:"bytes,1,opt,name=sandbox_uid,json=sandboxUid,proto3" json:"sandbox_uid,omitempty"`
	TargetPort    uint32                 `protobuf:"varint,2,opt,name=target_port,json=targetPort,proto3" json:"target_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueRouteCredentialRequest) Reset() {
	*x = IssueRouteCredentialRequest{}
	mi := &file_api_proto_v1_fastpath_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueRouteCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueRouteCredentialRequest) ProtoMessage() {}

func (x *IssueRouteCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_fastpath_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueRouteCredentialRequest.ProtoReflect.Descriptor instead.
func (*IssueRouteCredentialRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_fastpath_proto_rawDescGZIP(), []int{8}
}

func (x *IssueRouteCredentialRequest) GetSandboxUid() string {
	if x != nil {
		return x.SandboxUid
	}
	return ""
}

func (x *IssueRouteCredentialRequest) GetTargetPort() uint32 {
	if x != nil {
		return x.TargetPort
	}
	return 0
}

type IssueRouteCredentialResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Credential           string                 `protobuf:"bytes,1,opt,name=credential,proto3" json:"credential,omitempty"`
	ExpiresAtUnixSeconds int64                  `protobuf:"varint,2,opt,name=expires_at_unix_seconds,json=expiresAtUnixSeconds,proto3" json:"expires_at_unix_seconds,omitempty"`
	RouteGeneration      int64                  `protobuf:"varint,3,opt,name=route_generation,json=routeGeneration,proto3" json:"route_generation,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *IssueRouteCredentialResponse) Reset() {
	*x = IssueRouteCredentialResponse{}
	mi := &file_api_proto_v1_fastpath_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueRouteCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueRouteCredentialResponse) ProtoMessage() {}

func (x *IssueRouteCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_fastpath_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueRouteCredentialResponse.ProtoReflect.Descriptor instead.
func (*IssueRouteCredentialResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_fastpath_proto_rawDescGZIP(), []int{9}
}

func (x *IssueRouteCredentialResponse) GetCredential() string {
	if x != nil {
		return x.Credential
	}
	return ""
}

func (x *IssueRouteCredentialResponse) GetExpiresAtUnixSeconds() int64 {
	if x != nil {
		return x.ExpiresAtUnixSeconds
	}
	return 0
}

func (x *IssueRouteCredentialResponse) GetRouteGeneration() int64 {
	if x != nil {
		return x.RouteGeneration
	}
	return 0
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxName   string                 `protobuf:"bytes,1,opt,name=sandbox_name,json=sandboxName,proto3" json:"sandbox_name,omitempty"` // CRD name (user-provided)
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`                        // 可选，默认为 "default"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_api_proto_v1_fastpath_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_fastpath_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_fastpath_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteRequest) GetSandboxName() string {
	if x != nil {
		return x.SandboxName
	}
	return ""
}

func (x *DeleteRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_api_proto_v1_fastpath_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_fastpath_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_fastpath_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UpdateRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	SandboxName string                 `protobuf:"bytes,1,opt,name=sandbox_name,json=sandboxName,proto3" json:"sandbox_name,omitempty"` // CRD name (user-provided)
	Namespace   string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// 可更新字段 (only one at a time, except labels)
	//
	// Types that are valid to be assigned to Update:
	//
	//	*UpdateRequest_ExpireTimeSeconds
	//	*UpdateRequest_ResetRevision
	//	*UpdateRequest_FailurePolicy
	//	*UpdateRequest_RecoveryTimeoutSeconds
	Update isUpdateRequest_Update `protobuf_oneof:"update"`
	// 标签更新 (可以与其他字段同时更新)
	Labels        map[string]string `protobuf:"bytes,7,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_api_proto_v1_fastpath_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_fastpath_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_fastpath_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateRequest) GetSandboxName() string {
	if x != nil {
		return x.SandboxName
	}
	return ""
}

func (x *UpdateRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *UpdateRequest) GetUpdate() isUpdateRequest_Update {
	if x != nil {
		return x.Update
	}
	return nil
}

func (x *UpdateRequest) GetExpireTimeSeconds() int64 {
	if x != nil {
		if x, ok := x.Update.(*UpdateRequest_ExpireTimeSeconds); ok {
			return x.ExpireTimeSeconds
		}
	}
	return 0
}

func (x *UpdateRequest) GetResetRevision() string {
	if x != nil {
		if x, ok := x.Update.(*UpdateRequest_ResetRevision); ok {
			return x.ResetRevision
		}
	}
	return ""
}

func (x *UpdateRequest) GetFailurePolicy() FailurePolicy {
	if x != nil {
		if x, ok := x.Update.(*UpdateRequest_FailurePolicy); ok {
			return x.FailurePolicy
		}
	}
	return FailurePolicy_MANUAL
}

func (x *UpdateRequest) GetRecoveryTimeoutSeconds() int32 {
	if x != nil {
		if x, ok := x.Update.(*UpdateRequest_RecoveryTimeoutSeconds); ok {
			return x.RecoveryTimeoutSeconds
		}
	}
	return 0
}

func (x *UpdateRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type isUpdateRequest_Update interface {
	isUpdateRequest_Update()
}

type UpdateRequest_ExpireTimeSeconds struct {
	ExpireTimeSeconds int64 `protobuf:"varint,3,opt,name=expire_time_seconds,json=expireTimeSeconds,proto3,oneof"` // Unix timestamp, 0 = remove expiry
}

type UpdateRequest_ResetRevision struct {
	ResetRevision string `protobuf:"bytes,4,opt,name=reset_revision,json=resetRevision,proto3,oneof"` // ISO8601 timestamp, 触发重启
}

type UpdateRequest_FailurePolicy struct {
	FailurePolicy FailurePolicy `protobuf:"varint,5,opt,name=failure_policy,json=failurePolicy,proto3,enum=fastpath.v1.FailurePolicy,oneof"` // 更新故障策略
}

type UpdateRequest_RecoveryTimeoutSeconds struct {
	RecoveryTimeoutSeconds int32 `protobuf:"varint,6,opt,name=recovery_timeout_seconds,json=recoveryTimeoutSeconds,proto3,oneof"`
}

func (*UpdateRequest_ExpireTimeSeconds) isUpdateRequest_Update() {}

func (*UpdateRequest_ResetRevision) isUpdateRequest_Update() {}

func (*UpdateRequest_FailurePolicy) isUpdateRequest_Update() {}

func (*UpdateRequest_RecoveryTimeoutSeconds) isUpdateRequest_Update() {}

type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Sandbox       *SandboxInfo           `protobuf:"bytes,3,opt,name=sandbox,proto3" json:"sandbox,omitempty"` // 更新后的状态
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_api_proto_v1_fastpath_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_fastpath_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_fastpath_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateResponse) GetSandbox() *SandboxInfo {
	if x != nil {
		return x.Sandbox
	}
	return nil
}

var File_api_proto_v1_fastpath_proto protoreflect.FileDescriptor

const file_api_proto_v1_fastpath_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/proto/v1/fastpath.proto\x12\vfastpath.v1\"+\n" +
	"\vListRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\">\n" +
	"\fListResponse\x12.\n" +
	"\x05items\x18\x01 \x03(\v2\x18.fastpath.v1.SandboxInfoR\x05items\"M\n" +
	"\n" +
	"GetRequest\x12!\n" +
	"\fsandbox_name\x18\x01 \x01(\tR\vsandboxName\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\"\xf4\x01\n" +
	"\vSandboxInfo\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12!\n" +
	"\fsandbox_name\x18\b \x01(\tR\vsandboxName\x12\x14\n" +
	"\x05phase\x18\x02 \x01(\tR\x05phase\x12\x1f\n" +
	"\vfastlet_pod\x18\x03 \x01(\tR\n" +
	"fastletPod\x12\x1c\n" +
	"\tendpoints\x18\x04 \x03(\tR\tendpoints\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x14\n" +
	"\x05image\x18\x06 \x01(\tR\x05image\x12\x19\n" +
	"\bpool_ref\x18\a \x01(\tR\apoolRef\"\xc9\x03\n" +
	"\rCreateRequest\x12\x14\n" +
	"\x05image\x18\x01 \x01(\tR\x05image\x12\x19\n" +
	"\bpool_ref\x18\x02 \x01(\tR\apoolRef\x12'\n" +
	"\rexposed_ports\x18\x03 \x03(\x05B\x02\x18\x01R\fexposedPorts\x12\x18\n" +
	"\acommand\x18\x04 \x03(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x05 \x03(\tR\x04args\x12\x1c\n" +
	"\tnamespace\x18\x06 \x01(\tR\tnamespace\x12K\n" +
	"\x10consistency_mode\x18\a \x01(\x0e2\x1c.fastpath.v1.ConsistencyModeB\x02\x18\x01R\x0fconsistencyMode\x12\x12\n" +
	"\x04name\x18\b \x01(\tR\x04name\x128\n" +
	"\x04envs\x18\t \x03(\v2$.fastpath.v1.CreateRequest.EnvsEntryR\x04envs\x12\x1f\n" +
	"\vworking_dir\x18\n" +
	" \x01(\tR\n" +
	"workingDir\x12\x1d\n" +
	"\n" +
	"request_id\x18\v \x01(\tR\trequestId\x1a7\n" +
	"\tEnvsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb6\x01\n" +
	"\x0eCreateResponse\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12!\n" +
	"\fsandbox_name\x18\x04 \x01(\tR\vsandboxName\x12\x1f\n" +
	"\vfastlet_pod\x18\x02 \x01(\tR\n" +
	"fastletPod\x12 \n" +
	"\tendpoints\x18\x03 \x03(\tB\x02\x18\x01R\tendpoints\x12\x1f\n" +
	"\vsandbox_uid\x18\x05 \x01(\tR\n" +
	"sandboxUid\"v\n" +
	"\x16ResolveEndpointRequest\x12\x1f\n" +
	"\vsandbox_uid\x18\x01 \x01(\tR\n" +
	"sandboxUid\x12\x1f\n" +
	"\vtarget_port\x18\x02 \x01(\rR\n" +
	"targetPort\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\"\x8e\x03\n" +
	"\x17ResolveEndpointResponse\x12\x1f\n" +
	"\vsandbox_uid\x18\x01 \x01(\tR\n" +
	"sandboxUid\x12\x1f\n" +
	"\vtarget_port\x18\x02 \x01(\rR\n" +
	"targetPort\x12%\n" +
	"\x0eproxy_endpoint\x18\x03 \x01(\tR\rproxyEndpoint\x12d\n" +
	"\x10required_headers\x18\x04 \x03(\v29.fastpath.v1.ResolveEndpointResponse.RequiredHeadersEntryR\x0frequiredHeaders\x12)\n" +
	"\x10route_generation\x18\x05 \x01(\x03R\x0frouteGeneration\x125\n" +
	"\x17expires_at_unix_seconds\x18\x06 \x01(\x03R\x14expiresAtUnixSeconds\x1aB\n" +
	"\x14RequiredHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"_\n" +
	"\x1bIssueRouteCredentialRequest\x12\x1f\n" +
	"\vsandbox_uid\x18\x01 \x01(\tR\n" +
	"sandboxUid\x12\x1f\n" +
	"\vtarget_port\x18\x02 \x01(\rR\n" +
	"targetPort\"\xa0\x01\n" +
	"\x1cIssueRouteCredentialResponse\x12\x1e\n" +
	"\n" +
	"credential\x18\x01 \x01(\tR\n" +
	"credential\x125\n" +
	"\x17expires_at_unix_seconds\x18\x02 \x01(\x03R\x14expiresAtUnixSeconds\x12)\n" +
	"\x10route_generation\x18\x03 \x01(\x03R\x0frouteGeneration\"P\n" +
	"\rDeleteRequest\x12!\n" +
	"\fsandbox_name\x18\x01 \x01(\tR\vsandboxName\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\"*\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xb1\x03\n" +
	"\rUpdateRequest\x12!\n" +
	"\fsandbox_name\x18\x01 \x01(\tR\vsandboxName\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x120\n" +
	"\x13expire_time_seconds\x18\x03 \x01(\x03H\x00R\x11expireTimeSeconds\x12'\n" +
	"\x0ereset_revision\x18\x04 \x01(\tH\x00R\rresetRevision\x12C\n" +
	"\x0efailure_policy\x18\x05 \x01(\x0e2\x1a.fastpath.v1.FailurePolicyH\x00R\rfailurePolicy\x12:\n" +
	"\x18recovery_timeout_seconds\x18\x06 \x01(\x05H\x00R\x16recoveryTimeoutSeconds\x12>\n" +
	"\x06labels\x18\a \x03(\v2&.fastpath.v1.UpdateRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\b\n" +
	"\x06update\"x\n" +
	"\x0eUpdateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x122\n" +
	"\asandbox\x18\x03 \x01(\v2\x18.fastpath.v1.SandboxInfoR\asandbox*'\n" +
	"\x0fConsistencyMode\x12\b\n" +
	"\x04FAST\x10\x00\x12\n" +
	"\n" +
	"\x06STRONG\x10\x01*.\n" +
	"\rFailurePolicy\x12\n" +
	"\n" +
	"\x06MANUAL\x10\x00\x12\x11\n" +
	"\rAUTO_RECREATE\x10\x012\xc1\x04\n" +
	"\x0fFastPathService\x12H\n" +
	"\rCreateSandbox\x12\x1a.fastpath.v1.CreateRequest\x1a\x1b.fastpath.v1.CreateResponse\x12H\n" +
	"\rDeleteSandbox\x12\x1a.fastpath.v1.DeleteRequest\x1a\x1b.fastpath.v1.DeleteResponse\x12H\n" +
	"\rUpdateSandbox\x12\x1a.fastpath.v1.UpdateRequest\x1a\x1b.fastpath.v1.UpdateResponse\x12D\n" +
	"\rListSandboxes\x12\x18.fastpath.v1.ListRequest\x1a\x19.fastpath.v1.ListResponse\x12?\n" +
	"\n" +
	"GetSandbox\x12\x17.fastpath.v1.GetRequest\x1a\x18.fastpath.v1.SandboxInfo\x12\\\n" +
	"\x0fResolveEndpoint\x12#.fastpath.v1.ResolveEndpointRequest\x1a$.fastpath.v1.ResolveEndpointResponse\x12k\n" +
	"\x14IssueRouteCredential\x12(.fastpath.v1.IssueRouteCredentialRequest\x1a).fastpath.v1.IssueRouteCredentialResponseB&Z$fast-sandbox/api/proto/v1;fastpathv1b\x06proto3"

var (
	file_api_proto_v1_fastpath_proto_rawDescOnce sync.Once
	file_api_proto_v1_fastpath_proto_rawDescData []byte
)

func file_api_proto_v1_fastpath_proto_rawDescGZIP() []byte {
	file_api_proto_v1_fastpath_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_fastpath_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_fastpath_proto_rawDesc), len(file_api_proto_v1_fastpath_proto_rawDesc)))
	})
	return file_api_proto_v1_fastpath_proto_rawDescData
}

var file_api_proto_v1_fastpath_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_proto_v1_fastpath_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_api_proto_v1_fastpath_proto_goTypes = []any{
	(ConsistencyMode)(0),                 // 0: fastpath.v1.ConsistencyMode
	(FailurePolicy)(0),                   // 1: fastpath.v1.FailurePolicy
	(*ListRequest)(nil),                  // 2: fastpath.v1.ListRequest
	(*ListResponse)(nil),                 // 3: fastpath.v1.ListResponse
	(*GetRequest)(nil),                   // 4: fastpath.v1.GetRequest
	(*SandboxInfo)(nil),                  // 5: fastpath.v1.SandboxInfo
	(*CreateRequest)(nil),                // 6: fastpath.v1.CreateRequest
	(*CreateResponse)(nil),               // 7: fastpath.v1.CreateResponse
	(*ResolveEndpointRequest)(nil),       // 8: fastpath.v1.ResolveEndpointRequest
	(*ResolveEndpointResponse)(nil),      // 9: fastpath.v1.ResolveEndpointResponse
	(*IssueRouteCredentialRequest)(nil),  // 10: fastpath.v1.IssueRouteCredentialRequest
	(*IssueRouteCredentialResponse)(nil), // 11: fastpath.v1.IssueRouteCredentialResponse
	(*DeleteRequest)(nil),                // 12: fastpath.v1.DeleteRequest
	(*DeleteResponse)(nil),               // 13: fastpath.v1.DeleteResponse
	(*UpdateRequest)(nil),                // 14: fastpath.v1.UpdateRequest
	(*UpdateResponse)(nil),               // 15: fastpath.v1.UpdateResponse
	nil,                                  // 16: fastpath.v1.CreateRequest.EnvsEntry
	nil,                                  // 17: fastpath.v1.ResolveEndpointResponse.RequiredHeadersEntry
	nil,                                  // 18: fastpath.v1.UpdateRequest.LabelsEntry
}
var file_api_proto_v1_fastpath_proto_depIdxs = []int32{
	5,  // 0: fastpath.v1.ListResponse.items:type_name -> fastpath.v1.SandboxInfo
	0,  // 1: fastpath.v1.CreateRequest.consistency_mode:type_name -> fastpath.v1.ConsistencyMode
	16, // 2: fastpath.v1.CreateRequest.envs:type_name -> fastpath.v1.CreateRequest.EnvsEntry
	17, // 3: fastpath.v1.ResolveEndpointResponse.required_headers:type_name -> fastpath.v1.ResolveEndpointResponse.RequiredHeadersEntry
	1,  // 4: fastpath.v1.UpdateRequest.failure_policy:type_name -> fastpath.v1.FailurePolicy
	18, // 5: fastpath.v1.UpdateRequest.labels:type_name -> fastpath.v1.UpdateRequest.LabelsEntry
	5,  // 6: fastpath.v1.UpdateResponse.sandbox:type_name -> fastpath.v1.SandboxInfo
	6,  // 7: fastpath.v1.FastPathService.CreateSandbox:input_type -> fastpath.v1.CreateRequest
	12, // 8: fastpath.v1.FastPathService.DeleteSandbox:input_type -> fastpath.v1.DeleteRequest
	14, // 9: fastpath.v1.FastPathService.UpdateSandbox:input_type -> fastpath.v1.UpdateRequest
	2,  // 10: fastpath.v1.FastPathService.ListSandboxes:input_type -> fastpath.v1.ListRequest
	4,  // 11: fastpath.v1.FastPathService.GetSandbox:input_type -> fastpath.v1.GetRequest
	8,  // 12: fastpath.v1.FastPathService.ResolveEndpoint:input_type -> fastpath.v1.ResolveEndpointRequest
	10, // 13: fastpath.v1.FastPathService.IssueRouteCredential:input_type -> fastpath.v1.IssueRouteCredentialRequest
	7,  // 14: fastpath.v1.FastPathService.CreateSandbox:output_type -> fastpath.v1.CreateResponse
	13, // 15: fastpath.v1.FastPathService.DeleteSandbox:output_type -> fastpath.v1.DeleteResponse
	15, // 16: fastpath.v1.FastPathService.UpdateSandbox:output_type -> fastpath.v1.UpdateResponse
	3,  // 17: fastpath.v1.FastPathService.ListSandboxes:output_type -> fastpath.v1.ListResponse
	5,  // 18: fastpath.v1.FastPathService.GetSandbox:output_type -> fastpath.v1.SandboxInfo
	9,  // 19: fastpath.v1.FastPathService.ResolveEndpoint:output_type -> fastpath.v1.ResolveEndpointResponse
	11, // 20: fastpath.v1.FastPathService.IssueRouteCredential:output_type -> fastpath.v1.IssueRouteCredentialResponse
	14, // [14:21] is the sub-list for method output_type
	7,  // [7:14] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_proto_v1_fastpath_proto_init() }
func file_api_proto_v1_fastpath_proto_init() {
	if File_api_proto_v1_fastpath_proto != nil {
		return
	}
	file_api_proto_v1_fastpath_proto_msgTypes[12].OneofWrappers = []any{
		(*UpdateRequest_ExpireTimeSeconds)(nil),
		(*UpdateRequest_ResetRevision)(nil),
		(*UpdateRequest_FailurePolicy)(nil),
		(*UpdateRequest_RecoveryTimeoutSeconds)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_fastpath_proto_rawDesc), len(file_api_proto_v1_fastpath_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_fastpath_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_fastpath_proto_depIdxs,
		EnumInfos:         file_api_proto_v1_fastpath_proto_enumTypes,
		MessageInfos:      file_api_proto_v1_fastpath_proto_msgTypes,
	}.Build()
	File_api_proto_v1_fastpath_proto = out.File
	file_api_proto_v1_fastpath_proto_goTypes = nil
	file_api_proto_v1_fastpath_proto_depIdxs = nil
}
