// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: api/proto/v1/fastpath.proto

package fastpathv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FastPathService_CreateSandbox_FullMethodName        = "/fastpath.v1.FastPathService/CreateSandbox"
	FastPathService_DeleteSandbox_FullMethodName        = "/fastpath.v1.FastPathService/DeleteSandbox"
	FastPathService_UpdateSandbox_FullMethodName        = "/fastpath.v1.FastPathService/UpdateSandbox"
	FastPathService_ListSandboxes_FullMethodName        = "/fastpath.v1.FastPathService/ListSandboxes"
	FastPathService_GetSandbox_FullMethodName           = "/fastpath.v1.FastPathService/GetSandbox"
	FastPathService_ResolveEndpoint_FullMethodName      = "/fastpath.v1.FastPathService/ResolveEndpoint"
	FastPathService_IssueRouteCredential_FullMethodName = "/fastpath.v1.FastPathService/IssueRouteCredential"
)

// FastPathServiceClient is the client API for FastPathService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FastPathServiceClient interface {
	// CreateSandbox 极速创建沙箱，绕过 K8s 控制面延迟
	CreateSandbox(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	// DeleteSandbox 极速删除沙箱
	DeleteSandbox(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	// UpdateSandbox 更新沙箱配置（过期时间、重启、策略等）
	UpdateSandbox(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	// ListSandboxes 获取沙箱列表
	ListSandboxes(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	// GetSandbox 获取沙箱详情
	GetSandbox(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*SandboxInfo, error)
	// ResolveEndpoint resolves an authenticated proxy route for a target port.
	ResolveEndpoint(ctx context.Context, in *ResolveEndpointRequest, opts ...grpc.CallOption) (*ResolveEndpointResponse, error)
	// IssueRouteCredential refreshes a short-lived credential for an existing route.
	IssueRouteCredential(ctx context.Context, in *IssueRouteCredentialRequest, opts ...grpc.CallOption) (*IssueRouteCredentialResponse, error)
}

type fastPathServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFastPathServiceClient(cc grpc.ClientConnInterface) FastPathServiceClient {
	return &fastPathServiceClient{cc}
}

func (c *fastPathServiceClient) CreateSandbox(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, FastPathService_CreateSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fastPathServiceClient) DeleteSandbox(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, FastPathService_DeleteSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fastPathServiceClient) UpdateSandbox(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, FastPathService_UpdateSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fastPathServiceClient) ListSandboxes(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, FastPathService_ListSandboxes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fastPathServiceClient) GetSandbox(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*SandboxInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SandboxInfo)
	err := c.cc.Invoke(ctx, FastPathService_GetSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fastPathServiceClient) ResolveEndpoint(ctx context.Context, in *ResolveEndpointRequest, opts ...grpc.CallOption) (*ResolveEndpointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveEndpointResponse)
	err := c.cc.Invoke(ctx, FastPathService_ResolveEndpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fastPathServiceClient) IssueRouteCredential(ctx context.Context, in *IssueRouteCredentialRequest, opts ...grpc.CallOption) (*IssueRouteCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssueRouteCredentialResponse)
	err := c.cc.Invoke(ctx, FastPathService_IssueRouteCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FastPathServiceServer is the server API for FastPathService service.
// All implementations must embed UnimplementedFastPathServiceServer
// for forward compatibility.
type FastPathServiceServer interface {
	// CreateSandbox 极速创建沙箱，绕过 K8s 控制面延迟
	CreateSandbox(context.Context, *CreateRequest) (*CreateResponse, error)
	// DeleteSandbox 极速删除沙箱
	DeleteSandbox(context.Context, *DeleteRequest) (*DeleteResponse, error)
	// UpdateSandbox 更新沙箱配置（过期时间、重启、策略等）
	UpdateSandbox(context.Context, *UpdateRequest) (*UpdateResponse, error)
	// ListSandboxes 获取沙箱列表
	ListSandboxes(context.Context, *ListRequest) (*ListResponse, error)
	// GetSandbox 获取沙箱详情
	GetSandbox(context.Context, *GetRequest) (*SandboxInfo, error)
	// ResolveEndpoint resolves an authenticated proxy route for a target port.
	ResolveEndpoint(context.Context, *ResolveEndpointRequest) (*ResolveEndpointResponse, error)
	// IssueRouteCredential refreshes a short-lived credential for an existing route.
	IssueRouteCredential(context.Context, *IssueRouteCredentialRequest) (*IssueRouteCredentialResponse, error)
	mustEmbedUnimplementedFastPathServiceServer()
}

// UnimplementedFastPathServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFastPathServiceServer struct{}

func (UnimplementedFastPathServiceServer) CreateSandbox(context.Context, *CreateRequest) (*CreateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSandbox not implemented")
}
func (UnimplementedFastPathServiceServer) DeleteSandbox(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSandbox not implemented")
}
func (UnimplementedFastPathServiceServer) UpdateSandbox(context.Context, *UpdateRequest) (*UpdateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSandbox not implemented")
}
func (UnimplementedFastPathServiceServer) ListSandboxes(context.Context, *ListRequest) (*ListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSandboxes not implemented")
}
func (UnimplementedFastPathServiceServer) GetSandbox(context.Context, *GetRequest) (*SandboxInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSandbox not implemented")
}
func (UnimplementedFastPathServiceServer) ResolveEndpoint(context.Context, *ResolveEndpointRequest) (*ResolveEndpointResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveEndpoint not implemented")
}
func (UnimplementedFastPathServiceServer) IssueRouteCredential(context.Context, *IssueRouteCredentialRequest) (*IssueRouteCredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IssueRouteCredential not implemented")
}
func (UnimplementedFastPathServiceServer) mustEmbedUnimplementedFastPathServiceServer() {}
func (UnimplementedFastPathServiceServer) testEmbeddedByValue()                         {}

// UnsafeFastPathServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FastPathServiceServer will
// result in compilation errors.
type UnsafeFastPathServiceServer interface {
	mustEmbedUnimplementedFastPathServiceServer()
}

func RegisterFastPathServiceServer(s grpc.ServiceRegistrar, srv FastPathServiceServer) {
	// If the following call panics, it indicates UnimplementedFastPathServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FastPathService_ServiceDesc, srv)
}

func _FastPathService_CreateSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FastPathServiceServer).CreateSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FastPathService_CreateSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FastPathServiceServer).CreateSandbox(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FastPathService_DeleteSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FastPathServiceServer).DeleteSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FastPathService_DeleteSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FastPathServiceServer).DeleteSandbox(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FastPathService_UpdateSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FastPathServiceServer).UpdateSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FastPathService_UpdateSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FastPathServiceServer).UpdateSandbox(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FastPathService_ListSandboxes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FastPathServiceServer).ListSandboxes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FastPathService_ListSandboxes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FastPathServiceServer).ListSandboxes(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FastPathService_GetSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FastPathServiceServer).GetSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FastPathService_GetSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FastPathServiceServer).GetSandbox(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FastPathService_ResolveEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveEndpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FastPathServiceServer).ResolveEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FastPathService_ResolveEndpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FastPathServiceServer).ResolveEndpoint(ctx, req.(*ResolveEndpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FastPathService_IssueRouteCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueRouteCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FastPathServiceServer).IssueRouteCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FastPathService_IssueRouteCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FastPathServiceServer).IssueRouteCredential(ctx, req.(*IssueRouteCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FastPathService_ServiceDesc is the grpc.ServiceDesc for FastPathService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FastPathService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fastpath.v1.FastPathService",
	HandlerType: (*FastPathServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSandbox",
			Handler:    _FastPathService_CreateSandbox_Handler,
		},
		{
			MethodName: "DeleteSandbox",
			Handler:    _FastPathService_DeleteSandbox_Handler,
		},
		{
			MethodName: "UpdateSandbox",
			Handler:    _FastPathService_UpdateSandbox_Handler,
		},
		{
			MethodName: "ListSandboxes",
			Handler:    _FastPathService_ListSandboxes_Handler,
		},
		{
			MethodName: "GetSandbox",
			Handler:    _FastPathService_GetSandbox_Handler,
		},
		{
			MethodName: "ResolveEndpoint",
			Handler:    _FastPathService_ResolveEndpoint_Handler,
		},
		{
			MethodName: "IssueRouteCredential",
			Handler:    _FastPathService_IssueRouteCredential_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/v1/fastpath.proto",
}
