apiVersion: sandbox.fast.io/v1alpha1
kind: SandboxPool
metadata:
  name: gvisor-pool
spec:
  runtimeType: gvisor
  runtimeClassName: gvisor
  capacity:
    poolMin: 1
    poolMax: 1
    bufferMin: 0
  maxSandboxesPerPod: 5
  agentTemplate:
    spec:
      containers:
        - name: agent
          image: fast-sandbox/agent:dev
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "2"
              memory: "2Gi"