apiVersion: sandbox.fast.io/v1alpha1
kind: SandboxPool
metadata:
  name: kata-clh-execd-pool
  namespace: default
spec:
  runtime: kata-clh
  infraProfile: opensandbox-execd-quickstart
  sandboxResources:
    cpu: 250m
    memory: 256Mi
    pids: 128
  capacity:
    poolMin: 1
    poolMax: 3
    bufferMin: 0
    bufferMax: 0
  maxSandboxesPerPod: 5
  fastletTemplate:
    spec:
      containers:
      - name: fastlet
        image: fast-sandbox/fastlet:dev
        imagePullPolicy: IfNotPresent
