apiVersion: sandbox.fast.io/v1alpha1
kind: SandboxPool
metadata:
  name: kata-clh-pool
spec:
  runtime: kata-clh
  infraProfile: minimal
  sandboxResources:
    cpu: 250m
    memory: 256Mi
    pids: 128
  capacity:
    poolMin: 1
    poolMax: 3
    bufferMin: 0
    bufferMax: 0
  maxSandboxesPerPod: 5
  fastletTemplate:
    spec:
      containers:
      - name: fastlet
        image: fast-sandbox-fastlet:latest
        imagePullPolicy: IfNotPresent
        command: ["/fastlet"]
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "2"
            memory: "2Gi"
        securityContext:
          privileged: true
        volumeMounts:
        - name: containerd-run
          mountPath: /run/containerd
        - name: containerd-root
          mountPath: /var/lib/containerd
      volumes:
      - name: containerd-run
        hostPath:
          path: /run/containerd
          type: Directory
      - name: containerd-root
        hostPath:
          path: /var/lib/containerd
          type: Directory
