apiVersion: sandbox.fast.io/v1alpha1
kind: SandboxPool
metadata:
  name: gvisor-pool
spec:
  runtime: gvisor
  sandboxResources:
    cpu: 250m
    memory: 256Mi
    pids: 128
  capacity:
    poolMin: 1
    poolMax: 1
    bufferMin: 0
  maxSandboxesPerPod: 5
  fastletTemplate:
    spec:
      containers:
        - name: fastlet
          image: fast-sandbox/fastlet:dev
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "2"
              memory: "2Gi"
